### ISSUE TITLE
加密方法调用错误

### ISSUE THREAD

**Issue by SinPingWu** [laijinxian/flutter_3des_plugin#4]
```dart
  _getDesPassword(String password) async {
    await Flutter3desPlugin.encrypt('0123456789', '123').then((value) => {
     print(value)
    });
  }
```

上述方法调用出现如下的错误，而且包名中存在example，是没有正式的提供吗？

```shell
E/MethodChannel#flutter_3des_plugin(16151): Failed to handle method call
E/MethodChannel#flutter_3des_plugin(16151): java.lang.StringIndexOutOfBoundsException: length=10; index=16
E/MethodChannel#flutter_3des_plugin(16151): 	at java.lang.String.substring(String.java:2060)
E/MethodChannel#flutter_3des_plugin(16151): 	at com.example.flutter_3des_plugin.Flutter3desPlugin.onMethodCall(Flutter3desPlugin.java:48)
E/MethodChannel#flutter_3des_plugin(16151): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_3des_plugin(16151): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_3des_plugin(16151): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_3des_plugin(16151): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_3des_plugin(16151): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter_3des_plugin(16151): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter_3des_plugin(16151): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/MethodChannel#flutter_3des_plugin(16151): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_3des_plugin(16151): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter_3des_plugin(16151): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/flutter (16151): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, length=10; index=16, null)
```

**Comment by SinPingWu** [comment]
使用的是android模拟器

**Comment by laijinxian** [comment]
哥，你的key太简单了； 使用demo的key试试； 因为源码有对key做了截取； 后面我做个兼容吧！

**Comment by laijinxian** [comment]
key长度 最低是16位， 3des加密的原理是前8位和后8位相互加密解密得来的，所以最低是16位

**Comment by laijinxian** [comment]
key 的长度必须是8的倍数

**Comment by laijinxian** [comment]
@SinPingWu key 的长度必须是8的倍数
